# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Native Build 25

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build-native:
    name: Build JNI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: so
            build-cmd: |
              sudo apt-get update && sudo apt-get install -y cmake gcc g++
              cd nativememory
              mkdir build && cd build
              cmake .. && cmake --build .
              cp ../target/libs/libEclipseStoreNativeMemory.so ../libEclipseStoreNativeMemory-linux-x86_64.so
          - os: windows-latest
            ext: dll
            build-cmd: |
              cd nativememory
              mkdir build
              cd build
              cmake .. && cmake --build .
              copy ..\target\libs\Debug\EclipseStoreNativeMemory.dll ..\EclipseStoreNativeMemory.dll
          - os: macos-latest
            ext: dylib
            build-cmd: |
              cd nativememory
              mkdir build && cd build
              cmake .. && cmake --build .
              cp ../target/libs/libEclipseStoreNativeMemory.dylib ../libEclipseStoreNativeMemory-macos-x86_64.dylib


    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Generate JNI headers
        run: mvn compile --no-transfer-progress

      - name: Build native library
        run: ${{ matrix.build-cmd }}

      - name: Upload native library
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.os }}
          path: nativememory/libEclipseStoreNativeMemory-*.${{ matrix.ext }}
